# Generated by Django 3.2.11 on 2022-02-09 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.CharField(max_length=500)),
                ('reply_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.FloatField()),
                ('heading', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('thumbnail', models.FileField(upload_to='thumbnail')),
                ('course_title', models.CharField(max_length=200)),
                ('course_description', models.TextField(verbose_name='Course Overview')),
                ('batch', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('course_fee', models.PositiveIntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('CourseList', models.CharField(max_length=50, unique=True)),
                ('updatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Lesson_Name', models.CharField(max_length=200)),
                ('updatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField()),
                ('timestamp', models.CharField(max_length=10)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('question_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.FileField(blank=True, upload_to='Video/')),
                ('video_description', models.TextField(blank=True)),
                ('notes', models.FileField(blank=True, upload_to='Notes/')),
                ('updatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Lessons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.lesson')),
            ],
        ),
    ]
