# Generated by Django 3.2.11 on 2022-02-09 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, max_length=25)),
                ('added_to_cart', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirm', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Course.course')),
            ],
        ),
    ]
