# Generated by Django 3.2.11 on 2022-02-09 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('thumbnail', models.FileField(upload_to='exam-thumbnail')),
                ('Subject_Name', models.CharField(blank=True, max_length=500)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='Course.courselist')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('questions', models.TextField(blank=True, help_text='Enter the Question')),
                ('images', models.FileField(blank=True, upload_to='Quiz_Questions')),
                ('subjects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='Examination.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('option', models.TextField(blank=True, help_text='Enter the options')),
                ('imagesOptions', models.FileField(blank=True, help_text='Enter the Image options If required', upload_to='QuizImages')),
                ('is_correct_answer', models.BooleanField(default=False, help_text='Check if this image or option is correct answer for this question')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Options', to='Examination.question')),
            ],
        ),
    ]
