# Generated by Django 3.2.11 on 2022-02-09 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.CharField(blank=True, help_text='max 255 characters are allowed', max_length=255)),
                ('blog_title', models.CharField(help_text='max 255 characters are allowed', max_length=255)),
                ('thumbnail', models.FileField(help_text='Thumbnail for you post', upload_to='blogs/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.blogtype')),
            ],
        ),
    ]
